### ISSUE TITLE
No endless loop

### ISSUE THREAD

**Issue by creativ073** [jedrzejchalubek/glidejs#170]
Hi Jędrzej,
is possible to have a new option to stop the slider at the last slide?

Actually the slider go from last one back to the first one both in carousel and slider mode. I'm referring to both the swipe and keys navigation.

Thanks,
Andrea Colanicchia.

**Comment by jedrzejchalubek** [comment]
In `slider` mode, arrows are disabled on the first and last slide. Glide do not jumps to the start/end while being on this "edge cases", because arrows are disabled. The same thing is for swipes.

However, in `slider` mode, Glide go back from first/last slide to the end/start on keyboard arrows press and when autoplaying. This is what you are referring to?

**Comment by creativ073** [comment]
Exactly, arrow keys is the problem. :)

In addition, I added the [jQuery Mouse Wheel plugin](https://github.com/jquery/jquery-mousewheel) and I bound the mousewheel event to **go('<')** and **go('>')** method calls.

Probably, the best solution is to block the above calls on the first and last slides, respectively, so doesn't matter from which event the method call arrive (click, keypress, mousewheel, etc.) it will be always stopped.

**Comment by jedrzejchalubek** [comment]
New 3.0.0 version coming, feature requests for version 2.0 are suspended. Closing, sorry.

**Comment by VladykoDarya** [comment]
Hi! If google brought you here too, this problem solved here: https://github.com/glidejs/glide/issues/315#issuecomment-465100206
