### ISSUE TITLE
Disable expanding effect?

### ISSUE THREAD

**Issue by zackmax** [jedrzejchalubek/glidejs#172]
Hi! How do I disable the expanding effect on my slider? When I load a page with a slider, it's at a reduced height. Then, when I scroll down, the slider expands to it's full height. This does not always work though, especially if a user scrolls down before a page has completely loaded. I would like to disable this feature altogether, but I can't find anything in the documentation. This problem is more frequent on phones than desktop devices, but can happen on both.

Here is a link where you can see this effect happening: https://arlingtonvoice.com/arlington/community/2016/12/13/snowball-express-pulls-alley-cats-station-honor-military-families

**Comment by jedrzejchalubek** [comment]
Reduced height is caused, because slider is inited before images within slider are loaded. Glide do not check or wait for slides content (there is no buildin lazyloader).

You can disable autoheight via options `autoheight: false;` and set fixes height for slider in css.

Or, second option, refresh slider with API when image in the first slide is fully loaded.
